### PR TITLE
Fixed bugs in using the JSON-based configuration store by applications

### PR DESCRIPTION
**Pull request by iagaponenko**

### CODE REVIEW

**Comment by ktlim** [comment]
Are you sure it isn't confusing to have "", "0", "false", etc. treated as `true`?  Might it not be better to constrain the generators rather than making the acceptor so generous?

**Comment by n8pease** [comment]
I agree with K-T that it would probably be more intuitive if None-equivalent values of non-bool types would be interpreted as False. Perhaps you want to limit the types accepted to a set for which you can reasonably define this.

**Comment by iagaponenko** [comment]
@ktlim @n8pease I presume your comments are regrading this statement:
```
     *    2.2) for any other type the method always returns 'true', thus treating
     *         these kinds of parameters found in the store as 'boolean' values
     *         which are set to 'true'.
     *	
```
In essence, your suggestion is to treat any value found in the JSON-based ConfigStore similar to the Python's approach for implicit conversion of (any) values to the boolean type. So, I perfectly understand why you both asked the same question 😸 I must admit, I too thought about introducing a more elaborate treatment for values of the non-boolean parameters. Initially, I had the very same ideas you're proposing. However, in the end, I chose to rule out this option based on the following reasonings:

1) On the technical merits. The  JSON-based `ConfigStore` supports a variety of types which would have to be carefully evaluated in this way: `bool`, `int` (and alike), `float`, `string`, `array`, `struct`, `null` (a special placeholder for a value similar to SQL's `NULL`), and a few more. It was not totally obvious to me how to approach some of these types. For instance, what should I do if I have a vector? Should I return 'false' if the vector is empty? Or, should I rather throw an exception? Even for `string` it's not clear how to treat user inputs like:
```
'     '
'FaLse'
'   false.  '
'0000'
```
One would have to carefully study the Python language approach for treating those as booleans ... to implement the same in C++. Would it really worth an effort to bring Python rules into C++?

2) On the application's requirements. This was actually the main reason why I ruled out this idea. The package has only 4 command-line flags which are presented to `boost::program_options` like this:
```
        ("help,h",
         "Demystify program usage.")

        ("verbose,v",
         "Chatty output.")

        ((prefix + "no-quote").c_str(),
         po::value<std::string>(),
         "Disable CSV field quoting.")

        ("part.disable-chunks",
         "This flag if present would disable making chunk files in the output folder. "
         "It's meant to run the tool in the 'dry run' mode, validating input files, "
         "generating the objectId-to-chunk/sub-chunk index map.");
```
Note that none of those specifies a type or a range of values. And since no specific type is given then `boost::program_options` assumes them to be `std::string`. For any of those, the pre-`JSON` version of the package was doing just this:
```
if (vm.count('verbose') > 0) {
   // assuming the flags was provided
}
```
The bug fix addresses exactly this scenario. And I thought, what's written in the comment for rule "2.2" is sufficient for code readers to understand what the implementation does.

However, if we had to use this class (`ConfigStore`) in a broader context then we would probably had to revisit its contract and take more elaborate approach for treating values of some types.

In the end, I should also mention that I'm beginning to like the the combined `JSON` + `boost::program_options` approach for configuring applications (in general, not only in a context of this specific package). First of all, the API of such configuration facility is rather small and observable (compare it with the "heavy weight" `Configuration` of the Qserv's Replication & Ingest System). Secondly, it allows populating the `ConfigStore` from various sources (`JSON`, `boost::program_options`, explicit `set<T>(par, val)` methods, as well as potentially from `YAML` or even `init`-style `*.cfg` files) while preserving the same API to the client code. So, I thought making the `ConfigStore` a general purpose package to be used by other packages like `partition`, `qserv`, etc., wouldn't be a bad idea(?).

**Comment by andy-slac** [comment]
JSON already has a defined boolean type an literals. I think it has to be an error when someone on C++ asks for boolean/flag value but JSON contains anyhting else than `true` or `false` (which are different from `"true"`, `"false"`). I don't care what Python does for type conversion, we should avoid surprises on C++ side.

**Comment by iagaponenko** [comment]
@andy-slac that's all correct regarding parameters which are fed into `ConfigStore` from a `JSON` file or by explicitly calling method `ConfigSrore::set<T>(std::string const& parameter, T const& value)`. Parameters of the `bool` type set in either of this way is not a problem. A problem (or perhaps a "problem"?) which we're discussing here is about treating values reported by `boost::program_options` in the map-like structure `boost::program_options::variables_map`. As I have mentioned it earlier, the application defines 4 flags which have no explicit values, and they're of type `std::string` (this type is implicitly chosen by the implementation of the `boost::program_options` library if no specific type is provided by a user). For any of those 4 flags the flag's value (if any provided in the command-line) doesn't matter for the application (`sph-*` tools). What matters is a very presence of a flag in `ConfigStore`. See the code for further details.

**Comment by andy-slac** [comment]
If that is a flag (boolean) then string is not a correct type for it, I think you need to fix `boost::program_options` stuff.

**Comment by ktlim** [comment]
Indeed, my suggestion is not to handle all possible types but instead to define the proper type and reject all others.

**Comment by iagaponenko** [comment]
@andy-slac yes, I agree with you! That's a good possibility. I must admit, I also considered this option as an alternative to what I attempted with this fix. For a lack of any other inputs or requirements, both options would have the same effect on the application's behavior. A choice I was facing was in between:
1) allowing any parameter to be treated as a value-less flag if the parameter is found in `ConfigStore` (the proposed implementation)
2) or, enforcing strict restrictions on flags by requiring a client code to define flags like this:
```
        ("verbose,v",
         boost::program_options::bool_switch()->default_value(false),
         "Chatty output.")
```

Now, after this discussion the second option looks like a better alternative.

Everyone on the thread agrees?

**Comment by n8pease** [comment]
Looks good.

**Pull request merged**
